### ISSUE TITLE
Can't load the dll file

### ISSUE THREAD

**Issue by JonathanGoikhman** [binarly-io/efiXplorer#49]
Hi, I did everything according to the instructions. 
The loader part works OK, but the explorer part doesn't. I get the following error: 
LoadLibrary(C:\Program Files\IDA Pro 7.5 SP3\plugins\efiXplorer64.dll) error: The specified procedure could not be found.
C:\Program Files\IDA Pro 7.5 SP3\plugins\efiXplorer64.dll: can't load file

Thank you

**Comment by yeggor** [comment]
Hello. Thanks for the report. You are trying to use the latest version of the plugin on IDA Pro 7.5, but efiXplorer is written according to the latest version of idasdk and hexrays_sdk and only works on IDA 7.7.

I think the error `The specified procedure could not be found` is caused by the fact that for IDA version < 760 the Hex-Rays API pointer must be initialized inside the plugin code (`hexdsp_t *hexdsp = nullptr`).

So you can make some changes in the plugin code and rebuild it with idasdk and hexrays_sdk v75.
Alternatively, you can build the plugin with Hex-Rays analysis disabled (should work without additional fixes).
